# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

orbs:
  python: circleci/python@1.2

commands:
  setup_dependencies:
    description: "Install depenencies"
    parameters:
      after-deps:
        description: "Install dependencies"
        type: steps
        default: []
    steps:
      - run: 
          name: "Install open JDK"
          command: sudo add-apt-repository -y ppa:openjdk-r/ppa
      - run: 
          name: "Install qq"
          command: sudo apt-get -qq update
      - run: 
          name: "No install recommends for JDK"
          command: sudo apt-get install -y openjdk-8-jdk --no-install-recommends
      - run: 
          name: "Run Java Alternatives install for JDK"
          command: sudo update-java-alternatives -s java-1.8.0-openjdk-amd64
      - run:
          name: "Run pip install setup tools"
          command: pip install -U pip setuptools
      - run:  
          name: "Install Tox"
          command: pip install -U tox==3.13.0
      - run:  
          name: "Get Tox Envs"
          command: python scripts/get_tox_envs.py --plan $ALL_ENVS
      - run:  
          name: "Run Tox"
          command: tox --notest -e $(python scripts/get_tox_envs.py $ALL_ENVS); cat /home/circleci/project/.tox/spouse/log/spouse-1.log
      - steps: << parameters.after-deps >>

# We want to make sure we run this only on master branch, release, or when we make tags
run_complex: &run_complex
  filters:
    branches:
      only:
        - master
        - /release-v.*/
    tags:
      only: /.*/

jobs:

  Python36-Unit-Tests: 
    docker:
      - image: cimg/python:3.6
    environment:
      JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
      ALL_ENVS: --all

    steps:
      - checkout
      - setup_dependencies
      - run:
          name: "Run Tox"
          command:  tox -e $(python scripts/get_tox_envs.py $ALL_ENVS); cat /home/circleci/project/.tox/spouse/log/spouse-1.log

  

workflows:
  version: 2

  Unit-Tests:
    jobs:
      - Python36-Unit-Tests
    
